# Generated by Django 6.0.3 on 2026-04-14 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtimenotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='realtimenotification',
            name='notification_type',
            field=models.CharField(choices=[('new_announcement', 'Нове оголошення'), ('new_reaction', 'Нова реакція на оголошення'), ('system', 'Системне повідомлення')], max_length=20),
        ),
        migrations.AlterField(
            model_name='realtimenotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Вхід'), ('logout', 'Вихід'), ('announcement_view', 'Перегляд оголошення'), ('reaction_add', 'Додавання реакції'), ('reaction_change', 'Зміна реакції'), ('reaction_remove', 'Видалення реакції'), ('page_visit', 'Відвідування сторінки')], max_length=20),
        ),
    ]
